### ISSUE TITLE
Build photo proof feature.

### ISSUE THREAD

**Issue by ilynne** [kotisdesign/kotis-print-shop#1]
Allow user to take a photo and automatically save it to the job's files. Proof should be sent to approver.

Should probably hook into file uploader.

**Comment by ilynne** [comment]
@becker1, does a photo proof belong to a job or an order? I guessed job, but it's worth asking.

**Comment by becker1** [comment]
job

**Comment by ilynne** [comment]
Approve page should have:

1. An “Approve” button.
2. A select dropdown with the title “Other Options”:
 1. Approved with change
 2. Question
 3. Need to see new photo with change
 4. Need to adjust art
 5. Not Approved
3. If they choose anything in # 2 it opens the comments box. No comments allowed if they chose # 1.

@becker1 is working on the APIs
