### ISSUE TITLE
Use AWS key to view photo proof image

### ISSUE THREAD

**Issue by ilynne** [kotisdesign/kotis-print-shop#17]
Use a time-limited key to access photo proof images stored on AWS. Images should not be public.

Remove image from email -- should only be visible to authorized user on kps app.

**Comment by ilynne** [comment]
@becker1, the default time limit is 10 minutes. Is that good or should I change it to 20?

**Comment by becker1** [comment]
It should only need like 2 seconds, just the time between when it gets the key until it renders the HTML on the page. We should remove the image from the email itself. So 10 minutes will be fine.
