### ISSUE TITLE
Allow multiple images to be sent as one photo proof

### ISSUE THREAD

**Issue by ilynne** [kotisdesign/kotis-print-shop#26]
Photo proof should allow multiple images.

**Comment by ilynne** [comment]
@becker1, @bonhamjp, there are a few ways of handling this. Unfortunately, you can't take pictures using the camera and a single file field that accepts multiple images. You have the option of taking ONE photo or selecting multiple existing images. So the choices I see are:

Instruct the people taking the photos to take all of the photos first, then select them using the photo proof form. I don't like this option -- it would fill up the local device with images and add a step that I think slows down the process.

Use JS to add additional fields. I do like this option. We could use a "+" link to upload additional photos.

Opinions?

**Comment by becker1** [comment]
What if there were always two upload fields, can you use both of them and then hit "send" and it uploads both?

**Comment by ilynne** [comment]
Yes, that's why I like option #2. You can add one or more fields.

**Comment by ilynne** [comment]
... or, yes, just have two fields and only two. That would work, too.

**Comment by becker1** [comment]
Eoin suggested that they always take two photos. I think we should start with just adding a second field, since that would clearly be the easiest, and then we can see how that goes.

**Comment by ilynne** [comment]
Works for me. And it will lay the groundwork for the inevitable "but sometimes we want to take three pictures" scenario.
